[package]
name = "bottds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
serenity = { version = "0.12.0", features = ["collector"] }
shuttle-runtime = "0.39.0"
shuttle-secrets = "0.39.0"
shuttle-serenity = "0.39.0"
tokio = "1.26.0"
tracing = "0.1.37"
serde_json = "1.0.114"
